### ISSUE TITLE
Breaking on small screens

### ISSUE THREAD

**Issue by raphaelpor** [typeis/typeis.github.io#2]
I suggest to remove the <canvas> and use a orange background or a image.
What do you think?
[
![typeis js it s the smart and simple javascript type checker](https://cloud.githubusercontent.com/assets/8525863/20182608/74d94f66-a749-11e6-8145-1e40a1357c44.png)
](url)

**Comment by salihsagdilek** [comment]
yea you right, this site doesn't support responsive u just made it for basic info.
i will try your advice when i am free, or if someone sent me a pull request i will marge :)

**Comment by raphaelpor** [comment]
Cool!
I'll see if I can make this Pull Request. :wink:
